Update awake_start - refactored keep car awake
Add feedback and error handling for TeslaFi (similar to what was done with Tessie). New BLE method to keep car awake without Sentry Mode.

diff --git a/run/awake_start b/run/awake_start
--- a/run/awake_start
+++ b/run/awake_start
@@ -2,26 +2,76 @@
 
 if [[ ( -z "${TESLAFI_API_TOKEN:+x}" ) && ( -z "${TESSIE_API_TOKEN:+x}" ) && ( -z "${TESLA_BLE_VIN:+x}" ) ]]
 then
-  log "Not keeping car awake using Sentry Mode."
-else
+  log "Not configured to keeping car awake."
 
-  if [[ -z "${SENTRY_CASE:+x}" && -n "${TESLA_BLE_VIN:+x}" ]]
-  then
-    # If unset, BLE can assume mode 2
-    SENTRY_CASE=2
-  fi
+elif [[ -n "${TESLA_BLE_VIN:+x}" ]]
+then
+  # Use Tesla BLE API to keep car awake
 
+  function nudge {
+    while true
+    do
+      sleep 300
+      log "Telsa BLE: Nudging the car."
+      /root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" charge-port-close
+    done
+  }
+
+  log "Tesla BLE: Starting background task to keep car awake."
+  nudge &
+  echo $! > /tmp/keep_awake_task_pid
+
+elif [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) && ( -n "${TESSIE_API_TOKEN:+x}" ) ]]
+then
   case "${SENTRY_CASE}" in
     1)
       # Sentry Mode should already be enabled
-      log "Skip sending command to enable Sentry Mode."
+      log "Skipped sending command to enable Sentry Mode."
       ;;
     2)
       if [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) ]]
       # Use TeslaFi API to enable Sentry Mode
       then
-        curl -s -H "Authorization: Bearer $TESLAFI_API_TOKEN" "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=true&noWake=true"
+        http_response=$(curl -s -w "%{http_code}" \
+          -H "Authorization: Bearer $TESLAFI_API_TOKEN" \
+          -H "Accept: application/json" \
+          -H "User-Agent: github.com/marcone/teslausb" \
+          "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=true&noWake=true")
+
         log "TeslaFi: Command sent to enable Sentry Mode."
+
+        # Extract HTTP status code
+        http_status="${http_response: -3}"
+                
+        # Extract response body (excluding status code)
+        response_body="${http_response:0:${#http_response}-3}"
+
+        # Check if HTTP status code is not 200 (OK)
+        if [ "$http_status" != "200" ]
+        then
+          # Log an error
+          log "TeslaFi: Failed to set Sentry Mode. Check your TESLAFI_API_TOKEN is set correctly. If it is, your car may be offline or asleep."
+        else
+          # Check if the response is in JSON format
+          if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
+          then
+            log "TeslaFi: Failed to set Sentry Mode."
+          else
+            # Parse JSON and check if "result" is true
+            result1=$(jq -r '.response' <<<"$response_body")
+            result2=$(jq -r '.result' <<<"$result1")
+            request_counter=$(jq -r '.tesla_request_counter' <<<"$response_body")
+            commands=$(jq -r '.commands' <<<"$request_counter")
+
+            if [[ "$result2" = "true" ]]
+            then
+              log "TeslaFi: Sentry Mode Enabled. Monthly command counter = $commands."
+            else
+              log "TeslaFi: Failed to set Sentry Mode. Response data: $response_body"
+            fi
+          fi
+        fi
+
       elif [[ -n "${TESSIE_API_TOKEN:+x}" ]]
       # Use Tessie API to enable Sentry Mode
       then
@@ -42,7 +92,7 @@ else
         if [ "$http_status" != "200" ]
         then
           # Log an error
-          log "Tessie: Failed to set Sentry Mode. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may not have a good connection."
+          log "Tessie: Failed to set Sentry Mode. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may be offline."
         else
           # Check if the response is in JSON format
           if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
@@ -56,15 +106,6 @@ else
               log "Tessie: Failed to set Sentry Mode. Response data: $response_body"
             fi
           fi
-        fi
-      elif [[ -n "${TESLA_BLE_VIN:+x}" ]]
-      # Use Tesla BLE API to enable Sentry Mode
-      then
-        if /root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" sentry-mode on
-        then
-          log "Tesla BLE: Command sent to enable Sentry Mode."
-        else
-          log "Tesla BLE: Failed to set Sentry Mode."
         fi
       fi
       ;;
