Update awake_stop
Verbose TeslaFi statuses

diff --git a/run/awake_stop b/run/awake_stop
--- a/run/awake_stop
+++ b/run/awake_stop
@@ -3,8 +3,44 @@
 if [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) ]]
 # Use TeslaFi API to disable Sentry Mode
 then
-  curl -s -H "Authorization: Bearer $TESLAFI_API_TOKEN" "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=false&noWake=true"
-  log "TeslaFi: Command sent to disable Sentry Mode."
+  http_response=$(curl -s -w "%{http_code}" \
+      -H "Authorization: Bearer $TESLAFI_API_TOKEN" \
+      -H "Accept: application/json" \
+      -H "User-Agent: github.com/marcone/teslausb" \
+      "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=false&noWake=true")
+  
+    log "TeslaFi: Command sent to disable Sentry Mode."
+    # Extract HTTP status code
+    http_status="${http_response: -3}"
+            
+    # Extract response body (excluding status code)
+    response_body="${http_response:0:${#http_response}-3}"
+  
+    # Check if HTTP status code is not 200 (OK)
+    if [ "$http_status" != "200" ]
+    then
+      # Log an error
+      log "TeslaFi: Failed to set Sentry Mode. Check your TESLAFI_API_TOKEN is set correctly. If it is, your car may be offline or asleep."
+    else
+      # Check if the response is in JSON format
+      if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
+      then
+        log "TeslaFi: Failed to set Sentry Mode."
+      else
+        # Parse JSON and check if "result" is true
+        result1=$(jq -r '.response' <<<"$response_body")
+        result2=$(jq -r '.result' <<<"$result1")
+        request_counter=$(jq -r '.tesla_request_counter' <<<"$response_body")
+        commands=$(jq -r '.commands' <<<"$request_counter")
+  
+        if [[ "$result2" = "true" ]]
+        then
+          log "TeslaFi: Sentry Mode Disabled. Current TeslaFi monthly command counter = $commands"
+        else
+          log "TeslaFi: Failed to set Sentry Mode. Response data: $response_body"
+        fi
+      fi
+    fi
 elif [[ -n "${TESSIE_API_TOKEN:+x}" ]]
 # Use Tessie API to disable Sentry Mode
 then
