Update awake_start
This is for using TeslaFi to keep your car awake with sentry mode.

diff --git a/run/awake_start b/run/awake_start
--- a/run/awake_start
+++ b/run/awake_start
@@ -1,5 +1,11 @@
 #!/bin/bash -eu
 
+# Function to set Sentry Mode via TeslaFI
+function set_sentry_mode {
+  local sentry_mode=$1
+  curl -s -H "Authorization: Bearer $TESLAFI_API_TOKEN" "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=$sentry_mode"
+}
+
 if [[ ( ( ! -x /root/bin/tesla_api.py) || ( ! -s /mutable/cache.json ) ) && ( -z "${TESLAFI_API_TOKEN:+x}" ) && ( -z "${TESSIE_API_TOKEN:+x}" ) ]]
 then
   log "Not keeping car awake."
@@ -21,7 +27,7 @@ function ping {
       fi
     fi
 
-    if [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) ]]
+    if [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) && ("$TESLAFI_WAKE_MODE" == "stream" ) ]] 
     # Use TeslaFi API to keep car awake.
     then
       curl -s -H "Authorization: Bearer $TESLAFI_API_TOKEN" "https://www.teslafi.com/feed.php?command=wake_up"
@@ -32,43 +38,43 @@ function ping {
     if [[ -n "${TESSIE_API_TOKEN:+x}" ]]
     # Use Tessie API to keep car awake
     then
-        http_response=$(curl -s -w "%{http_code}" \
-            -H "Authorization: Bearer $TESSIE_API_TOKEN" \
-            -H "Accept: application/json" \
-            -H "User-Agent: github.com/marcone/teslausb" \
-            "https://api.tessie.com/$TESSIE_VIN/wake")
-        
-        # Extract HTTP status code
-        http_status="${http_response: -3}"
-        
-        # Extract response body (excluding status code)
-        response_body="${http_response:0:${#http_response}-3}"
-        
-        # Check if HTTP status code is not 200 (OK)
-        if [ "$http_status" != "200" ]
+      http_response=$(curl -s -w "%{http_code}" \
+        -H "Authorization: Bearer $TESSIE_API_TOKEN" \
+        -H "Accept: application/json" \
+        -H "User-Agent: github.com/marcone/teslausb" \
+        "https://api.tessie.com/$TESSIE_VIN/wake")
+      
+      # Extract HTTP status code
+      http_status="${http_response: -3}"
+      
+      # Extract response body (excluding status code)
+      response_body="${http_response:0:${#http_response}-3}"
+      
+      # Check if HTTP status code is not 200 (OK)
+      if [ "$http_status" != "200" ]
+      then
+        # Log an error
+        log "Failed to wake car with Tessie API. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may not have a good connection. Retrying in 1 minute..."
+        sleep 60
+      else
+        # Check if the response is in JSON format
+        if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
         then
-            # Log an error
-            log "Failed to wake car with Tessie API. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may not have a good connection. Retrying in 1 minute..."
-            sleep 60
+          log "Failed to wake car with Tessie API. Retrying in 1 minute. Response data: $response_body"
+          sleep 60
         else
-            # Check if the response is in JSON format
-            if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
-            then
-                log "Failed to wake car with Tessie API. Retrying in 1 minute. Response data: $response_body"
-                sleep 60
-            else
-                # Parse JSON and check if "result" is true
-                result=$(jq -r '.result' <<<"$response_body")
-                if [[ "$result" != "true" ]]
-                then
-                    log "Failed to wake car with Tessie API. Retrying in 1 minute. Response data: $response_body"
-                    sleep 60
-                else
-                    # Sleep for 5 minutes on successful wake-up call
-                    sleep 300
-                fi
-            fi
+          # Parse JSON and check if "result" is true
+          result=$(jq -r '.result' <<<"$response_body")
+          if [[ "$result" != "true" ]]
+          then
+            log "Failed to wake car with Tessie API. Retrying in 1 minute. Response data: $response_body"
+            sleep 60
+          else
+            # Sleep for 5 minutes on successful wake-up call
+            sleep 300
+          fi
         fi
+      fi
     fi
   done
 }
@@ -78,13 +84,23 @@ case "${TESLA_WAKE_MODE:-stream}" in
     is_sentry_mode_enabled=$(/root/bin/tesla_api.py is_sentry_mode_enabled | tr '[:upper:]' '[:lower:]')
     if [ "false" = "${is_sentry_mode_enabled}" ]
     then
-      log "Temporarily enabling Sentry Mode to keep car awake."
-      touch /tmp/disable_sentry_after_archiving
-      /root/bin/tesla_api.py enable_sentry_mode &>> "${LOG_FILE}"
+      # Check if TESLAFI_WAKE_MODE is set to sentry
+      if [ "$TESLAFI_WAKE_MODE" == "sentry" ]; then
+        log "Turning on Sentry Mode to keep car awake (via TeslaFI)."
+        set_sentry_mode true
+        echo "sentry_enabled" > /tmp/sentry_state  # Log Sentry state
+      else
+        log "Turning on Sentry Mode to keep car awake (via Tesla API)."
+        /root/bin/tesla_api.py enable_sentry_mode &>> "${LOG_FILE}"
+        echo "sentry_enabled" > /tmp/sentry_state  # Log Sentry state
+      fi
+    else
+      log "Sentry Mode is already enabled."
+      echo "sentry_already_enabled" > /tmp/sentry_state  # Log Sentry state
     fi
     ;;
   stream)
-    log "Starting background task to keep car awake."
+    log "Starting background tasks to keep TeslaUSB powered on during archiving." 
     ping &
     echo $! > /tmp/keep_awake_task_pid
     ;;
